name: Build_6_12_6

on:
    workflow_dispatch:

jobs:
    compile:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        
        - name: Install Dependencies
          run:  | 
            sudo apt install -y git linux-firmware curl wget gcc bison make cmake build-essential libncurses-dev flex libelf-dev bc kmod cpio flex libncurses5-dev libelf-dev libssl-dev dwarves bison fakeroot tree debhelper-compat
            mkdir ./kernel
          
        - name: Fetch source
          working-directory: ./kernel          
          run:  |
            wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.12.6.tar.xz

        - name: Extract Tarball
          working-directory: ./kernel
          run:  |
            tar -xf linux-6.12.6.tar.xz
            sudo chown -R $(whoami):$(whoami) linux-6.12.6
            
        - name: Clean Kernel tree
          working-directory: ./kernel/linux-6.12.6
          run: make mrproper      

        - name: Get CPU Core Count
          run: nproc
          
        - name: Configure and Make
          working-directory:  ./kernel/linux-6.12.6
          run: |
            wget https://raw.githubusercontent.com/thegamershollow/stoney-kernel/refs/heads/main/kernel-config -O .config
            make olddefconfig
            make -j`nproc`
        
        - name: Build Debian Package
          working-directory: ./kernel/linux-6.12.6
          run: |
            make bindeb-pkg
        
        - name: Build Tar Archive
          working-directory: ./kernel/linux-6.12.6
          run: |
            make targz-pkg
        
        - name: Build Fedora Package
          working-directory: ./kernel/linux-6.12.6
          run: |
            make binrpm-pkg
            
        - name: Upload Debian Kernel Headers
          uses: actions/upload-artifact@v3
          with:
              name: "Debian Kernel Headers"
              path: ./kernel/linux-6.12.6/linux-headers-6.12.6_6.12.6-2_amd64.deb
       
        - name: Upload Debian Kernel Image
          uses: actions/upload-artifacts@v3
          with:
              name: "Debian Kernel Image"
              path: ./kernel/linux-image-6.12.6_6.12.6-2_amd64.deb
        - name: Upload Kernel Tarball
          uses: actions/artifacts@v3
          with:
              name: "Kernel Tarball"
              path: ./kernel/linux-6.12.6.tar.xz
        
        - name: view dir tree
          working-directory: ./kernel
          run: tree -L 2
        - name: view home dir
          working-directory: ~/
          run: tree -L 2
          
